# Stage 1: App Build
FROM python:3.12.0-slim-bullseye as coyote3_dev_app

LABEL base_image="python:3.12-slim"
LABEL about.home="https://github.com/Clinical-Genomics-Lund/coyote3"

# Expose Flask app port
EXPOSE 8000

# Set working directory
WORKDIR /app

# System environment variables (hardcoded, do not change often)
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV FLASK_APP=wsgi.py

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libxml2-dev libxslt1-dev zlib1g-dev libsasl2-dev libldap2-dev \
    build-essential libssl-dev libffi-dev libjpeg-dev libpq-dev \
    liblcms2-dev libblas-dev libatlas-base-dev libglib2.0-dev \
    libpango1.0-0 less vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Python requirements
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Create logs directory
RUN mkdir ./logs
RUN mkdir ./redis_data

# Copy source code
COPY config/ ./config/
COPY config.py wsgi.py gunicorn.conf.py logging_setup.py ./
COPY .coyote3_dev_env ./.env
COPY coyote/ ./coyote/
COPY docs/ ./docs/
COPY CHANGELOG.md README.md LICENSE.txt ./

# Runtime environment variables that should be overridden by docker-compose.yml or .env file
ENV SCRIPT_NAME="/coyote3_dev"

# Gunicorn command (you can override with `command:` in docker-compose if needed)
#CMD ["gunicorn", "--timeout", "120", "-w", "2", "-e", "SCRIPT_NAME", "--log-level", "INFO", "--bind", "0.0.0.0:8000", "wsgi:app"]
CMD gunicorn --timeout 240 -w 2 --threads 2 -e SCRIPT_NAME=${SCRIPT_NAME} --log-level DEBUG --bind 0.0.0.0:8000 wsgi:app

