[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Coyote2"
version = "1.0.0.Alpha"
description = "A Bioinformatics Interpretation and Analysis Tool built for Section for Molecular Diagnostics, Region Skåne, Lund, Sweden"
dependencies = [
    "arrow==1.3.0",
    "black==24.4.2",
    "click==8.1.7",
    "dnspython==2.6.1",
    "email_validator==2.2.0",
    "flake8==7.1.0",
    "Flask==3.0.3",
    "Flask-Cors==4.0.1",
    "Flask-LDAPConn==0.10.2",
    "Flask-Login==0.6.3",
    "Flask-PyMongo==2.3.0",
    "Flask-WTF==1.2.1",
    "gunicorn==22.0.0",
    "isort==5.13.2",
    "itsdangerous==2.2.0",
    "Jinja2==3.1.4",
    "Markdown==3.6",
    "MarkupSafe==2.1.5",
    "mongomock==4.1.2",
    "mypy==1.11.0",
    "mypy-extensions==1.0.0",
    "pre-commit==3.7.1",
    "pyflakes==3.2.0",
    "pymongo==3.13.0",
    "pytest==8.3.2",
    "pytest-mock==3.14.0",
    "python-dateutil==2.9.0.post0",
    "six==1.16.0",
    "toml==0.10.2",
    "Werkzeug==3.0.3",
    "WTForms==3.1.2"
]

[tool.black]
line-length = 79
target-version = ['py312']
skip-string-normalization = false
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''



[tool.flake8]
max-line-length = 100
exclude = ".git,__pycache__,build,dist"

[tool.isort]
profile = "black"
