"""Repository port for home/read and sample settings flows."""

from __future__ import annotations

from typing import Protocol


class HomeRepository(Protocol):
    def get_samples(
        self,
        *,
        user_assays: list,
        user_envs: list,
        status: str,
        report: bool,
        search_str: str,
        limit: int | None,
        offset: int,
        use_cache: bool,
        reload: bool,
    ) -> list[dict]: ...

    def get_isgl_by_asp(self, **query) -> list[dict]: ...
    def get_isgl_by_ids(self, ids: list[str]) -> dict: ...
    def get_asp(self, assay: str) -> dict: ...
    def get_asp_genes(self, assay: str) -> tuple[list, list]: ...
    def reset_sample_settings(self, sample_id: str, filters: dict) -> None: ...
    def get_sample(self, sample_id: str) -> dict | None: ...
    def get_variant_stats(self, sample_id: str, genes: list[str] | None = None) -> dict: ...
    def update_sample_filters(self, sample_id: str, filters: dict) -> None: ...
    def get_report(self, sample_id: str, report_id: str) -> dict: ...
