"""Ports for security/auth data access."""

from __future__ import annotations

from typing import Any, Protocol


class SecurityRepository(Protocol):
    def get_role(self, role_id: str | None) -> dict[str, Any] | None: ...

    def get_all_roles(self) -> list[dict[str, Any]]: ...

    def get_all_active_asps(self) -> list[dict[str, Any]]: ...

    def get_user_by_username(self, username: str) -> dict[str, Any] | None: ...

    def get_user_by_id(self, user_id: str) -> dict[str, Any] | None: ...

    def get_sample(self, sample_id: str) -> dict[str, Any] | None: ...

    def get_sample_by_id(self, sample_id: str) -> dict[str, Any] | None: ...

    def update_user_last_login(self, user_id: str) -> None: ...
