#!/usr/bin/env python3
"""Generate system permission and role references from the bootstrap catalogs."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE = REPO_ROOT / "api/config/bootstrap/rbac/permissions.seed.ndjson"
OUTPUT = REPO_ROOT / "docs/administration/permission-catalog.md"
ROLE_SOURCE = REPO_ROOT / "api/config/bootstrap/rbac/roles.seed.ndjson"
ROLE_OUTPUT = REPO_ROOT / "docs/administration/system-role-catalog.md"


def _escape(value: Any) -> str:
    """Prepare a permission value for a single Markdown table cell.

    Args:
        value: Catalog field value; falsey values are rendered as empty text.

    Returns:
        Stripped text with pipes escaped and newlines replaced by spaces.
    """
    return str(value or "").replace("|", "\\|").replace("\n", " ").strip()


def main() -> int:
    """Regenerate permission and role references from the bundled NDJSON catalogs.

    Returns:
        Zero after writing the repository's permission catalog Markdown and printing
        its path. Categories and permission IDs are sorted alphabetically.

    Raises:
        json.JSONDecodeError: A nonblank catalog line is malformed JSON.
        KeyError: A permission record lacks ``permission_id``.
        OSError: The catalog cannot be read or the reference cannot be written.
    """
    permissions = [
        json.loads(line) for line in SOURCE.read_text(encoding="utf-8").splitlines() if line.strip()
    ]
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for permission in permissions:
        grouped[str(permission.get("category") or "Other")].append(permission)

    lines = [
        "# System permission catalog",
        "",
        "<!-- MACHINE GENERATED: DO NOT EDIT THIS FILE DIRECTLY. -->",
        "",
        "> **Generated reference**",
        ">",
        "> This page is generated from `api/config/bootstrap/rbac/permissions.seed.ndjson` by",
        "> `scripts/docs/export_permissions_reference.py`. Edit the bootstrap catalog and regenerate this page.",
        "",
        "Coyote3 installs these permissions into an empty database. They are application contracts:",
        "administrators can assign them through center-owned roles, but cannot edit, deactivate,",
        "or delete installed definitions. Catalog updates use the controlled installation tools.",
        "",
    ]
    for category in sorted(grouped):
        lines.extend(
            [
                f"## {category}",
                "",
                "| Permission ID | Label | What it permits |",
                "| --- | --- | --- |",
            ]
        )
        for permission in sorted(grouped[category], key=lambda item: item["permission_id"]):
            lines.append(
                f"| `{_escape(permission['permission_id'])}` | {_escape(permission.get('label'))} | "
                f"{_escape(permission.get('description'))} |"
            )
        lines.append("")

    OUTPUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"[ok] wrote {OUTPUT.relative_to(REPO_ROOT)}")
    roles = sorted(
        [
            json.loads(line)
            for line in ROLE_SOURCE.read_text(encoding="utf-8").splitlines()
            if line.strip()
        ],
        key=lambda role: role["role_id"],
    )
    role_lines = [
        "# System role catalog",
        "",
        "<!-- MACHINE GENERATED: DO NOT EDIT THIS FILE DIRECTLY. -->",
        "",
        "These roles are installed from `api/config/bootstrap/rbac/roles.seed.ndjson`.",
        "This reference is generated by `scripts/docs/export_permissions_reference.py`.",
        "",
        "Installed roles are protected definitions. Assign them to accounts or create center-owned",
        "roles for a different combination of permissions. Assay/environment access scopes still",
        "apply; a permission grant does not by itself grant access to every clinical sample.",
        "The `superuser` role bypasses normal access policies and is reserved for emergency access.",
        "",
        "Query-rule and reporting-rule workflows have separate grants. Assign independent people",
        "to authoring and review; granting both roles does not waive the independence checks.",
        "",
        "| Role ID | Label | Responsibility | Grants |",
        "| --- | --- | --- | --- |",
    ]
    for role in roles:
        role_lines.append(
            f"| [`{role['role_id']}`](#{role['role_id'].replace('_', '-')}) | {_escape(role.get('label'))} | "
            f"{_escape(role.get('description'))} | {len(role.get('permissions', []))} |"
        )
    role_lines.extend(
        [
            "",
            "## Permission assignments",
            "",
            "See the [permission catalog](permission-catalog.md) for each operation's meaning.",
            "",
        ]
    )
    for role in roles:
        role_lines.extend(
            [
                f"### {role['role_id'].replace('_', '-')}",
                "",
                "Role: `" + role["role_id"] + "`. " + _escape(role.get("description")),
                "",
            ]
        )
        role_lines.extend(
            "- `" + permission + "`" for permission in sorted(role.get("permissions", []))
        )
        if not role.get("permissions"):
            role_lines.append("No explicit permissions are assigned by this role.")
        role_lines.append("")
    ROLE_OUTPUT.write_text("\n".join(role_lines).rstrip() + "\n", encoding="utf-8")
    print(f"[ok] wrote {ROLE_OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
