#!/usr/bin/env python3
"""Export DB collection contracts from Pydantic models into docs markdown."""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any, get_origin

# Ensure repo root is importable when running as `python scripts/...`.
REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


def _field_type_name(annotation: Any) -> str:
    """Render a field annotation while retaining generic type parameters.

    Args:
        annotation: Runtime annotation obtained from a Pydantic model field.

    Returns:
        Class name or simplified annotation text without ``typing.`` prefixes;
        outer ``Optional`` annotations use ``| None`` notation.
    """
    # On Python 3.10, `list[str]` / `dict[str, int]` can satisfy
    # `isinstance(annotation, type)`. Guard with `get_origin` so we don't lose
    # generic parameters and generate unstable docs across Python versions.
    if isinstance(annotation, type) and get_origin(annotation) is None:
        return annotation.__name__
    text = str(annotation)
    text = text.replace("typing.", "").replace("<class '", "").replace("'>", "")
    text = re.sub(r"^Optional\[(.+)\]$", r"\1 | None", text)
    return text


def export_query_condition_fields() -> None:
    """Render the query builder's field/type/operator catalog from its authoritative registry."""
    from api.domain.query_conditions import condition_catalog

    catalog = condition_catalog()
    lines = [
        "# Query condition field catalog",
        "",
        "Generated by `scripts/docs/export_collection_contracts_doc.py` from the application-owned",
        "query-condition registry. Change the registry and regenerate this page.",
        "",
        "Use these stored field paths in the [query-rule builder](../administration/query-rules.md).",
        "Fields are case-sensitive. Object-array children can be matched independently using dotted",
        "paths, or within one element using **Match the same array element**. Identity and access",
        "fields are not authorable. The API returns this catalog at",
        "`GET /api/v1/admin/query-rule-sets/options` under `conditions`.",
        "",
        "Text comparisons preserve case and whitespace. Numeric comparisons require JSON numbers;",
        "quoted numbers are not converted. A string-list comparison matches its elements.",
        "",
    ]
    for analysis, fields in catalog["fields"].items():
        lines += [
            f"## {analysis.upper()}",
            "",
            "| Field | Stored type | Allowed operators | Sample filter references |",
            "| --- | --- | --- | --- |",
        ]
        for field in fields:
            operators = ", ".join(f"`${operator}`" for operator in field["operators"])
            references = ", ".join(f"`{ref['key']}`" for ref in field["filter_references"]) or "—"
            lines.append(
                f"| `{field['path']}` | {field['kind'].replace('_', ' ')} | {operators} | {references} |"
            )
        lines.append("")
    path = Path("docs/reference/query-condition-fields.md")
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[ok] wrote {path}")


def main() -> int:
    """Overwrite the collection-contract reference from registered Pydantic adapters.

    Returns:
        Zero after writing ``docs/reference/mongodb-collections.md`` relative to the
        working directory and printing its path.

    Raises:
        OSError: The output directory is missing or the Markdown file cannot be written.

    Notes:
        Orders collections alphabetically and fields in model declaration order.
        Does not connect to MongoDB.
    """
    from api.contracts.schemas.registry import COLLECTION_MODEL_ADAPTERS

    adapters = COLLECTION_MODEL_ADAPTERS
    lines: list[str] = []
    lines.append("# MongoDB collection contracts")
    lines.append("")
    lines.append("<!-- MACHINE GENERATED: DO NOT EDIT THIS FILE DIRECTLY. -->")
    lines.append("")
    lines.append(
        "> **Generated reference**\n>\n"
        "> Generated from `api/contracts/schemas/registry.py` by "
        "`scripts/docs/export_collection_contracts_doc.py`. Change the schema or generator, "
        "then regenerate this page."
    )
    lines.append("")
    lines.append("This is the canonical collection-key reference used by ingestion validation.")
    lines.append("")
    lines.append("## Cross-collection relations")
    lines.append("")
    lines.append(
        "- `samples.asp_id` must match `asp_configs.asp_id` and `assay_specific_panels.asp_id`."
    )
    lines.append(
        "- Initial ASPC resolution uses `samples.asp_id`, `samples.subpanel_id`, and "
        "`samples.environment`; the resolved ObjectId/key and `aspc_resolution` are persisted on the sample."
    )
    lines.append(
        "- `insilico_genelists.asp_ids[]` and `asp_groups[]` must map to ASP/ASPC assay setup; "
        "`diagnosis[]` carries its reusable diagnosis/in-silico-subpanel tags."
    )
    lines.append("- `roles.permissions[]` must reference `permissions.permission_id`.")
    lines.append("- `users.roles[]` must reference `roles.role_id`.")
    lines.append("")
    lines.append("## DNA vs RNA sample rules")
    lines.append("")
    lines.append(
        "- `omics_layer=DNA` allows only DNA file keys: `vcf_files`, `cnv`, `cnvprofile`, `cov`, `biomarkers`, `transloc`, `pgx`."
    )
    lines.append(
        "- `omics_layer=RNA` allows only RNA file keys: `fusion_files`, `expression_path`, `classification_path`, `qc`, `pgx`."
    )
    lines.append("- Mixed DNA+RNA file-key payloads are rejected by model validation.")
    lines.append("")

    for collection in sorted(adapters):
        model = adapters[collection]._type  # type: ignore[attr-defined]
        fields = getattr(model, "model_fields", {})
        required = []
        optional = []
        for name, field in fields.items():
            ftype = _field_type_name(field.annotation)
            entry = f"`{name}` ({ftype})"
            if field.is_required():
                required.append(entry)
            else:
                optional.append(entry)
        lines.append(f"## `{collection}`")
        lines.append("")
        lines.append("Required keys:")
        if required:
            for item in required:
                lines.append(f"- {item}")
        else:
            lines.append("- None")
        lines.append("")
        lines.append("Optional keys:")
        if optional:
            for item in optional:
                lines.append(f"- {item}")
        else:
            lines.append("- None")
        lines.append("")
        if collection == "oncokb_public":
            lines.append(
                "Sample identity fields such as `sample_ids` and `sample_names` are forbidden. "
                "This shared cache stores only normalized queries and public responses."
            )
            lines.append("")

    out_path = Path("docs/reference/mongodb-collections.md")
    out_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"[ok] wrote {out_path}")
    export_query_condition_fields()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
