import { useState } from "react"
import type { FocusEvent, MouseEvent, ReactNode } from "react"

import { DetailHero } from "@/components/detail/FindingDetailLayout"
import { TooltipSurface } from "@/components/ui/app-tooltip"
import { TimeDisplay } from "@/components/ui/time-display"
import { sampleReported } from "@/lib/sample-shape"

function displayValue(value: unknown) {
  if (value === undefined || value === null || value === "") return "-"
  return String(value)
}

function tooltipPosition(event: MouseEvent | FocusEvent) {
  const rect = event.currentTarget.getBoundingClientRect()
  const width = 288
  const height = 116
  const gap = 8
  const edge = 8
  const left = Math.min(
    Math.max(rect.left + rect.width / 2 - width / 2, edge),
    Math.max(edge, window.innerWidth - width - edge),
  )
  const hasRoomBelow = rect.bottom + gap + height <= window.innerHeight - edge
  const top = Math.min(
    Math.max(hasRoomBelow ? rect.bottom + gap : rect.top - height - gap, edge),
    Math.max(edge, window.innerHeight - height - edge),
  )
  return { left, top }
}

function metricDescription(label: string) {
  if (label === "FFPE") return "The case material is recorded as formalin-fixed, paraffin-embedded tissue."
  if (label === "Purity") return "Estimated tumor purity for the case sample."
  if (label.startsWith("MSI")) return "Microsatellite instability signal calculated from the sample biomarker output."
  if (label === "HRD") return "Homologous recombination deficiency summary score."
  return "Sample-level result generated by the configured analysis workflow."
}

function MetricBadge({
  label,
  value,
  details,
}: {
  label: string
  value: ReactNode
  details?: string
}) {
  const [position, setPosition] = useState<{ left: number; top: number } | null>(null)
  return (
    <span
      className="inline-flex"
      data-tooltip-managed="true"
      onMouseEnter={(event) => setPosition(tooltipPosition(event))}
      onMouseMove={(event) => setPosition(tooltipPosition(event))}
      onMouseLeave={() => setPosition(null)}
      onFocus={(event) => setPosition(tooltipPosition(event))}
      onBlur={() => setPosition(null)}
    >
      <span
        tabIndex={0}
        className="inline-flex cursor-help items-center gap-1 rounded-md border border-sand-300/70 bg-sand-100 px-1.5 py-0.5 type-meta font-medium text-foreground shadow-sm outline-none focus:ring-2 focus:ring-ring/40 dark:border-sand-400/25 dark:bg-sand-900/40"
      >
        <span className="text-muted-foreground">{label}:</span>
        {value}
      </span>
      {position && (
        <TooltipSurface position={position} className="border-sand-300/80 text-sand-950 dark:border-sand-400/30 dark:text-sand-100">
          <span className="mb-1 block type-label font-semibold uppercase tracking-wide opacity-80">Sample metric</span>
          <span className="block font-semibold text-foreground">{label}</span>
          <span className="mt-1 block type-meta leading-relaxed text-foreground/75">{metricDescription(label)}</span>
          {details && <span className="mt-1 block type-meta font-medium text-foreground/85">{details}</span>}
        </TooltipSurface>
      )}
    </span>
  )
}

function StatusBadge({
  children,
  tone,
}: {
  children: ReactNode
  tone: "info" | "success" | "warning" | "danger" | "neutral"
}) {
  const toneClass = {
    info: "badge-info",
    success: "badge-success",
    warning: "badge-warning",
    danger: "badge-danger",
    neutral: "badge-neutral",
  }[tone]

  return <span className={`type-badge ${toneClass}`}>{children}</span>
}

function numberValue(value: unknown) {
  const numeric = Number(value)
  return Number.isFinite(numeric) ? numeric : null
}

function purityPercentage(value: unknown) {
  const purity = numberValue(value)
  if (purity === null) return null
  const percentage = purity >= 0 && purity <= 1 ? purity * 100 : purity
  return `${Number(percentage.toFixed(2))}%`
}

function buildSampleMetricBadges(sample: any, context: any) {
  const biomarkerPayload = context?.display_sections_data?.biomarkers ?? context?.biomarkers
  const biomarkers = Array.isArray(biomarkerPayload)
    ? biomarkerPayload
    : biomarkerPayload && typeof biomarkerPayload === "object"
      ? [biomarkerPayload]
      : []
  const badges: ReactNode[] = []

  biomarkers.forEach((marker: any, index: number) => {
    for (const [key, label] of [["MSIS", "MSI (Single)"], ["MSIP", "MSI (Paired)"]] as const) {
      const value = numberValue(marker?.[key]?.per)
      if (value !== null) {
        badges.push(
          <MetricBadge
            key={`${key}-${index}`}
            label={label}
            value={`${value}%`}
            details={`Total: ${displayValue(marker[key].tot)}; Somatic: ${displayValue(marker[key].som)}`}
          />,
        )
      }
    }
    const hrd = numberValue(marker?.HRD?.sum)
    if (hrd !== null) {
      badges.push(
        <MetricBadge
          key={`HRD-${index}`}
          label="HRD"
          value={hrd}
          details={`TAI: ${displayValue(marker.HRD.tai)}; HRD: ${displayValue(marker.HRD.hrd)}; LST: ${displayValue(marker.HRD.lst)}`}
        />,
      )
    }
  })

  const purity = purityPercentage(sample?.case?.purity ?? sample?.purity)
  if (purity !== null) badges.push(<MetricBadge key="purity" label="Purity" value={purity} />)
  if (sample?.case?.ffpe === true) badges.push(<MetricBadge key="ffpe" label="FFPE" value="Yes" />)

  return badges
}

function ingestStatusTone(status: string): "success" | "danger" | "neutral" {
  if (status === "ready") return "success"
  if (["failed", "error", "partial"].includes(status)) return "danger"
  return "neutral"
}

export function SampleDetailHero({ sample, context }: { sample: any; context: any }) {
  const status = String(sample?.ingest_status || "").toLowerCase()
  const metricBadges = buildSampleMetricBadges(sample, context)
  const caseId = sample?.case_id || sample?.case?.id
  const controlId = sample?.control_id || sample?.control?.id
  return (
    <DetailHero
      backTo="/samples"
      density="compact"
      eyebrow={[sample?.asp_id, sample?.subpanel_id, sample?.environment].filter(Boolean).join(" • ")}
      title={sample?.name || sample?.case_id || sample?._id || "Sample"}
      chips={metricBadges.length > 0 ? metricBadges : undefined}
      actions={
        <div className="flex min-w-52 flex-col items-end gap-2">
          <dl className="type-meta grid gap-1 text-muted-foreground md:text-right">
            {caseId && (
              <div className="flex gap-1.5 md:justify-end">
                <dt className="font-medium text-foreground">Case</dt>
                <dd>{caseId}</dd>
              </div>
            )}

            {controlId && (
              <div className="flex gap-1.5 md:justify-end">
                <dt className="font-medium text-foreground">Control</dt>
                <dd>{controlId}</dd>
              </div>
            )}

            {sample?.time_added && (
              <div className="flex gap-1.5 md:justify-end">
                <dt className="font-medium text-foreground">Added</dt>
                <dd>
                  <TimeDisplay value={sample.time_added} mode="full" />
                </dd>
              </div>
            )}
          </dl>

          <div className="flex flex-wrap items-center gap-1.5 md:justify-end">
            <StatusBadge tone={sample?.paired ? "success" : "warning"}>
              {sample?.paired ? "Paired" : "Unpaired"}
            </StatusBadge>

            {sample?.ingest_status && (
              <StatusBadge tone={ingestStatusTone(status)}>
                {sample.ingest_status}
              </StatusBadge>
            )}

            {sample?.archived && (
              <StatusBadge tone="danger">Archived</StatusBadge>
            )}

            <StatusBadge tone={sampleReported(sample) ? "info" : "warning"}>
              {sampleReported(sample) ? "Reported" : "Unreported"}
            </StatusBadge>
          </div>
        </div>
      }
    />
  )
}
