"""Ports for admin workflows."""

from __future__ import annotations

from typing import Any, Protocol


class AdminSampleDeletionRepository(Protocol):
    def get_sample_by_id(self, sample_id: str) -> dict[str, Any] | None: ...

    def delete_sample_variants(self, sample_id: str) -> Any: ...

    def delete_sample_cnvs(self, sample_id: str) -> Any: ...

    def delete_sample_coverage(self, sample_id: str) -> Any: ...

    def delete_sample_panel_coverage(self, sample_id: str) -> Any: ...

    def delete_sample_translocs(self, sample_id: str) -> Any: ...

    def delete_sample_fusions(self, sample_id: str) -> Any: ...

    def delete_sample_biomarkers(self, sample_id: str) -> Any: ...

    def delete_sample(self, sample_id: str) -> Any: ...
