"""Ports for DNA reporting workflows."""

from __future__ import annotations

from typing import Any, Protocol


class DNAReportingRepository(Protocol):
    def get_asp(self, asp_name: str) -> dict[str, Any] | None: ...

    def get_isgl_by_asp(self, assay: str, *, is_active: bool = True) -> list[dict[str, Any]]: ...

    def get_isgl_by_ids(self, genelists: list[str]) -> list[dict[str, Any]]: ...

    def get_case_variants(self, query: dict[str, Any]) -> list[dict[str, Any]]: ...

    def add_blacklist_data(self, variants: list[dict[str, Any]], assay: str) -> list[dict[str, Any]]: ...

    def get_latest_sample_comment(self, sample_id: str) -> dict[str, Any] | None: ...

    def get_interesting_sample_cnvs(self, sample_id: str) -> list[dict[str, Any]]: ...

    def get_sample_biomarkers(self, sample_id: str) -> list[dict[str, Any]]: ...

    def get_interesting_sample_translocations(self, sample_id: str) -> list[dict[str, Any]]: ...

    def get_variant_class_translations(self, vep_version: int) -> dict[str, Any]: ...

