"""Repository port for dashboard read models."""

from __future__ import annotations

from typing import Protocol


class DashboardRepository(Protocol):
    def count_users(self) -> int: ...
    def count_roles(self, is_active: bool | None = None) -> int: ...
    def count_asps(self, is_active: bool | None = None) -> int: ...
    def count_aspcs(self, is_active: bool | None = None) -> int: ...
    def count_isgls(self) -> int: ...

    def get_all_isgl(self) -> list[dict]: ...
    def get_all_users(self) -> list[dict]: ...
    def get_user_by_id(self, user_id: str) -> dict | None: ...
    def get_all_active_asps(self) -> list[dict]: ...

    def get_dashboard_sample_rollup(self, assays: list[str] | None) -> dict: ...
    def get_dashboard_variant_counts(self) -> dict: ...
    def get_total_cnv_count(self) -> int: ...
    def get_total_transloc_count(self) -> int: ...
    def get_total_fusion_count(self) -> int: ...
    def get_unique_blacklist_count(self) -> int: ...
    def get_dashboard_tier_stats(self) -> dict: ...
    def get_all_asps_unique_gene_count(self) -> int: ...
    def get_all_asp_gene_counts(self) -> dict: ...
