access_log syslog:server=monitor:5514,tag=docs,severity=info combined;
error_log syslog:server=monitor:5514,tag=docs error;
server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }
}
