"""Domain-oriented DB document contracts."""

from api.contracts.schemas.assay import (
    AspConfigDoc,
    AssaySpecificPanelsDoc,
    BlacklistDoc,
    InsilicoGenelistsDoc,
)
from api.contracts.schemas.base import VersionHistoryEntryDoc, _DocBase
from api.contracts.schemas.dna import (
    BiomarkersDoc,
    CnvGeneDoc,
    CnvsDoc,
    GeneCoverageDoc,
    GroupCoverageDoc,
    PanelCovDoc,
    ReportedVariantsDoc,
    TranslocationsDoc,
    VariantCsqDoc,
    VariantGtDoc,
    VariantInfoDoc,
    VariantsDoc,
)
from api.contracts.schemas.governance import PermissionsDoc, RolesDoc, UsersDoc
from api.contracts.schemas.reference import (
    AnnotationDoc,
    BrcaExchangeDoc,
    CivicGenesDoc,
    CivicVariantsDoc,
    CosmicDoc,
    DashboardMetricsDoc,
    HgncGenesDoc,
    HpaExprDoc,
    IarcTp53Doc,
    ManeSelectDoc,
    OncoKbActionableDoc,
    OncoKbCancerGenesPublicDoc,
    OncoKbGenesDoc,
    OncoKbGenesPublicDoc,
    OncoKbPublicDoc,
    RefSeqCanonicalDoc,
    VepMetadataDoc,
)
from api.contracts.schemas.registry import (
    COLLECTION_MODEL_ADAPTERS,
    normalize_collection_document,
    supported_collections,
    validate_collection_document,
)
from api.contracts.schemas.rna import FusionsDoc, RnaClassificationDoc, RnaExpressionDoc, RnaQcDoc
from api.contracts.schemas.samples import (
    SampleCaseControlDoc,
    SampleCommentRecordDoc,
    SampleReportRecordDoc,
    SamplesDoc,
)

__all__ = [
    "_DocBase",
    "VersionHistoryEntryDoc",
    "SampleCaseControlDoc",
    "SampleCommentRecordDoc",
    "SampleReportRecordDoc",
    "SamplesDoc",
    "VariantCsqDoc",
    "VariantInfoDoc",
    "VariantGtDoc",
    "VariantsDoc",
    "CnvGeneDoc",
    "CnvsDoc",
    "TranslocationsDoc",
    "BiomarkersDoc",
    "GeneCoverageDoc",
    "PanelCovDoc",
    "GroupCoverageDoc",
    "FusionsDoc",
    "RnaExpressionDoc",
    "RnaClassificationDoc",
    "RnaQcDoc",
    "UsersDoc",
    "RolesDoc",
    "PermissionsDoc",
    "AnnotationDoc",
    "ReportedVariantsDoc",
    "AspConfigDoc",
    "AssaySpecificPanelsDoc",
    "InsilicoGenelistsDoc",
    "BlacklistDoc",
    "BrcaExchangeDoc",
    "CivicGenesDoc",
    "CivicVariantsDoc",
    "CosmicDoc",
    "DashboardMetricsDoc",
    "HgncGenesDoc",
    "HpaExprDoc",
    "IarcTp53Doc",
    "ManeSelectDoc",
    "OncoKbActionableDoc",
    "OncoKbCancerGenesPublicDoc",
    "OncoKbGenesDoc",
    "OncoKbPublicDoc",
    "OncoKbGenesPublicDoc",
    "RefSeqCanonicalDoc",
    "VepMetadataDoc",
    "COLLECTION_MODEL_ADAPTERS",
    "validate_collection_document",
    "normalize_collection_document",
    "supported_collections",
]
