"""Ports for workflow services."""

from __future__ import annotations

from typing import Any, Protocol


class RNAWorkflowRepository(Protocol):
    def update_sample_filters(self, sample_id: str, filters: dict[str, Any]) -> None: ...

    def get_sample_by_id(self, sample_id: str) -> dict[str, Any] | None: ...

    def get_isgl_by_ids(self, isgl_ids: list[str]) -> dict[str, Any]: ...

    def get_rna_expression(self, sample_id: str) -> dict[str, Any] | None: ...

    def get_rna_classification(self, sample_id: str) -> dict[str, Any] | None: ...

    def get_rna_qc(self, sample_id: str) -> dict[str, Any] | None: ...

    def get_fusion_in_other_samples(self, fusion: dict[str, Any]) -> list[dict[str, Any]]: ...

    def get_global_annotations(
        self,
        selected_fusion_call: dict[str, Any],
        assay_group: str,
        subpanel: str | None,
    ) -> tuple[Any, Any, Any, Any]: ...

    def hidden_fusion_comments(self, fusion_id: str) -> Any: ...

    def get_asp_group_mappings(self) -> dict[str, Any]: ...

    def get_sample_fusions(self, fusion_query: dict[str, Any]) -> list[dict[str, Any]]: ...

    def get_fusion_annotations(self, fusion: dict[str, Any]) -> tuple[Any, Any]: ...

