name: coyote3_test

services:
  frontend:
    image: coyote3-frontend:${COYOTE3_VERSION:-local}-test
    profiles: [with-ui]
  docs:
    image: coyote3-docs:${COYOTE3_VERSION:-local}-test
    profiles: [with-ui]
  api:
    image: coyote3-api:${COYOTE3_VERSION:-local}-test
    build:
      dockerfile: docker/Dockerfile.dev
      target: coyote3_dev_api
  worker:
    image: coyote3-api:${COYOTE3_VERSION:-local}-test
    build:
      dockerfile: docker/Dockerfile.dev
      target: coyote3_dev_api
  beat:
    image: coyote3-api:${COYOTE3_VERSION:-local}-test
    build:
      dockerfile: docker/Dockerfile.dev
      target: coyote3_dev_api
  proxy:
    profiles: [with-ui]
    ports: ["${COYOTE3_PORT:-6811}:8088"]
  test_runner:
    image: coyote3-all:${COYOTE3_VERSION:-local}-test
    profiles: [tests]
    build:
      context: ../..
      dockerfile: docker/Dockerfile.dev
      target: coyote3_dev_all
    environment:
      ENV_NAME: ${ENV_NAME:?ENV_NAME is required}
      MONGO_URI: ${MONGO_URI:?MONGO_URI is required}
      COYOTE3_DB: ${COYOTE3_DB:?COYOTE3_DB is required}
      BAM_DB: ${BAM_DB:?BAM_DB is required}
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    command: bash -lc 'PYTHONPATH=. pytest -q'
    networks: [app]
    depends_on:
      api: {condition: service_healthy}
