#!/usr/bin/env python3
"""Generate the system permission reference from the bootstrap catalog."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE = REPO_ROOT / "api/config/bootstrap/rbac/permissions.seed.ndjson"
OUTPUT = REPO_ROOT / "docs/developer/permission_catalog.md"


def _escape(value: Any) -> str:
    return str(value or "").replace("|", "\\|").replace("\n", " ").strip()


def main() -> int:
    permissions = [
        json.loads(line) for line in SOURCE.read_text(encoding="utf-8").splitlines() if line.strip()
    ]
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for permission in permissions:
        grouped[str(permission.get("category") or "Other")].append(permission)

    lines = [
        "# System permission catalog",
        "",
        "<!-- MACHINE GENERATED: DO NOT EDIT THIS FILE DIRECTLY. -->",
        "",
        '!!! info "Source of truth"',
        "    This page is generated from `api/config/bootstrap/rbac/permissions.seed.ndjson` by",
        "    `scripts/export_permissions_reference.py`. Edit the bootstrap catalog and regenerate this page.",
        "",
        "Coyote3 installs these permissions into an empty database. They are application contracts:",
        "administrators can assign them through roles, but cannot rename or delete them. A disabled",
        "permission grants no access until it is reactivated.",
        "",
    ]
    for category in sorted(grouped):
        lines.extend(
            [
                f"## {category}",
                "",
                "| Permission ID | Label | What it permits |",
                "| --- | --- | --- |",
            ]
        )
        for permission in sorted(grouped[category], key=lambda item: item["permission_id"]):
            lines.append(
                f"| `{_escape(permission['permission_id'])}` | {_escape(permission.get('label'))} | "
                f"{_escape(permission.get('description'))} |"
            )
        lines.append("")

    OUTPUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"[ok] wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
