"""Domain-organized typed models for web API payloads."""

from coyote.integrations.api.api_models.base import ApiMutationResultPayload
from coyote.integrations.api.api_models.auth import (
    ApiAuthLoginPayload,
    ApiAuthMePayload,
    ApiAuthSessionUserPayload,
)
from coyote.integrations.api.api_models.dashboard import ApiDashboardSummaryPayload
from coyote.integrations.api.api_models.common import (
    ApiCommonGeneInfoPayload,
    ApiCommonTieredVariantPayload,
    ApiCommonTieredVariantSearchPayload,
)
from coyote.integrations.api.api_models.coverage import (
    ApiCoverageBlacklistedPayload,
    ApiCoverageSamplePayload,
)
from coyote.integrations.api.api_models.home import (
    ApiHomeSamplesPayload,
    ApiHomeIsglsPayload,
    ApiHomeEffectiveGenesPayload,
    ApiHomeEditContextPayload,
    ApiHomeReportContextPayload,
)
from coyote.integrations.api.api_models.public import (
    ApiPublicGenelistViewContextPayload,
    ApiPublicAspGenesPayload,
    ApiPublicAssayCatalogGenesViewPayload,
    ApiPublicAssayCatalogMatrixContextPayload,
    ApiPublicAssayCatalogContextPayload,
    ApiPublicAssayCatalogCsvContextPayload,
)
from coyote.integrations.api.api_models.internal import (
    ApiInternalIsglMetaPayload,
    ApiInternalRoleLevelsPayload,
)
from coyote.integrations.api.api_models.admin import (
    ApiAdminPermissionContextPayload,
    ApiAdminPermissionCreateContextPayload,
    ApiAdminPermissionsPayload,
    ApiAdminGenelistContextPayload,
    ApiAdminGenelistCreateContextPayload,
    ApiAdminGenelistsPayload,
    ApiAdminGenelistViewContextPayload,
    ApiAdminAspContextPayload,
    ApiAdminAspCreateContextPayload,
    ApiAdminAspPayload,
    ApiAdminAspcContextPayload,
    ApiAdminAspcCreateContextPayload,
    ApiAdminAspcPayload,
    ApiAdminSampleContextPayload,
    ApiAdminSamplesPayload,
    ApiAdminRoleContextPayload,
    ApiAdminRoleCreateContextPayload,
    ApiAdminRolesPayload,
    ApiAdminSchemaContextPayload,
    ApiAdminSchemasPayload,
    ApiAdminUserContextPayload,
    ApiAdminUserCreateContextPayload,
    ApiAdminUsersPayload,
)
from coyote.integrations.api.api_models.dna import (
    ApiDnaPlotContextPayload,
    ApiDnaBiomarkersPayload,
    ApiDnaCnvsPayload,
    ApiDnaCnvDetailPayload,
    ApiDnaReportPreviewPayload,
    ApiDnaReportSavePayload,
    ApiDnaTranslocationsPayload,
    ApiDnaTranslocationDetailPayload,
    ApiDnaVariantDetailPayload,
    ApiDnaVariantsPayload,
)
from coyote.integrations.api.api_models.rna import (
    ApiRnaFusionDetailPayload,
    ApiRnaFusionsPayload,
    ApiRnaReportPreviewPayload,
    ApiRnaReportSavePayload,
)

__all__ = [
    "ApiMutationResultPayload",
    "ApiAuthLoginPayload",
    "ApiAuthMePayload",
    "ApiAuthSessionUserPayload",
    "ApiDashboardSummaryPayload",
    "ApiCommonGeneInfoPayload",
    "ApiCommonTieredVariantPayload",
    "ApiCommonTieredVariantSearchPayload",
    "ApiCoverageSamplePayload",
    "ApiCoverageBlacklistedPayload",
    "ApiHomeSamplesPayload",
    "ApiHomeIsglsPayload",
    "ApiHomeEffectiveGenesPayload",
    "ApiHomeEditContextPayload",
    "ApiHomeReportContextPayload",
    "ApiPublicGenelistViewContextPayload",
    "ApiPublicAspGenesPayload",
    "ApiPublicAssayCatalogGenesViewPayload",
    "ApiPublicAssayCatalogMatrixContextPayload",
    "ApiPublicAssayCatalogContextPayload",
    "ApiPublicAssayCatalogCsvContextPayload",
    "ApiInternalIsglMetaPayload",
    "ApiInternalRoleLevelsPayload",
    "ApiAdminRolesPayload",
    "ApiAdminRoleCreateContextPayload",
    "ApiAdminRoleContextPayload",
    "ApiAdminPermissionsPayload",
    "ApiAdminPermissionCreateContextPayload",
    "ApiAdminPermissionContextPayload",
    "ApiAdminUsersPayload",
    "ApiAdminUserCreateContextPayload",
    "ApiAdminUserContextPayload",
    "ApiAdminSchemasPayload",
    "ApiAdminSchemaContextPayload",
    "ApiAdminGenelistsPayload",
    "ApiAdminGenelistCreateContextPayload",
    "ApiAdminGenelistContextPayload",
    "ApiAdminGenelistViewContextPayload",
    "ApiAdminAspPayload",
    "ApiAdminAspCreateContextPayload",
    "ApiAdminAspContextPayload",
    "ApiAdminAspcPayload",
    "ApiAdminAspcCreateContextPayload",
    "ApiAdminAspcContextPayload",
    "ApiAdminSamplesPayload",
    "ApiAdminSampleContextPayload",
    "ApiDnaPlotContextPayload",
    "ApiDnaBiomarkersPayload",
    "ApiDnaCnvsPayload",
    "ApiDnaCnvDetailPayload",
    "ApiDnaReportPreviewPayload",
    "ApiDnaReportSavePayload",
    "ApiDnaTranslocationsPayload",
    "ApiDnaTranslocationDetailPayload",
    "ApiDnaVariantDetailPayload",
    "ApiDnaVariantsPayload",
    "ApiRnaFusionDetailPayload",
    "ApiRnaFusionsPayload",
    "ApiRnaReportPreviewPayload",
    "ApiRnaReportSavePayload",
]
