name: "Version Change Check"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check_version_updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if __version__.py was updated and version line changed
        run: |
          echo "🔍 Checking if coyote/__version__.py was modified..."
          if git diff --name-only origin/main...HEAD | grep -q 'coyote/__version__.py'; then
            echo "File modified. Checking if __version__ line was updated..."
            if git diff origin/main...HEAD -- coyote/__version__.py | grep -q '__version__'; then
              echo "__version__ line was modified. Version update detected."
            else
              echo "coyote/__version__.py was modified but __version__ line was not updated."
              exit 1
            fi
          else
            echo "coyote/__version__.py was not modified. Please update the version."
            exit 1
          fi
