[primary]
    users_collection = "users"
    roles_collection = "roles"
    permissions_collection = "permissions"
    notifications_collection = "notifications"

    insilico_genelist_collection = "insilico_genelists"
    aspc_collection = "asp_configs"
    asp_collection = "assay_specific_panels"

    blacklist_collection = "blacklist"
    annotations_collection = "annotation"
    samples_collection = "samples"
    sample_comments_collection = "sample_comments"
    reports_collection = "reports"
    variants_collection = "variants"
    anno_vep_collection = "anno_vep"
    cnvs_collection = "cnvs"
    fusions_collection = "fusions"
    transloc_collection = "translocations"
    biomarkers_collection = "biomarkers"
    pgx_collection = "pgx"
    coverage_collection = "panel_coverage"
    groupcov_collection = "group_coverage"
    rna_expression_collection = "rna_expression"
    rna_qc_collection = "rna_qc"
    rna_classification_collection = "rna_classification"
    reported_variants_collection = "reported_variants"

    vep_metadata_collection = "vep_metadata"
    hgnc_collection = "hgnc_genes"

    civic_variants_collection = "civic_variants"
    civic_gene_collection = "civic_genes"
    oncokb_collection = "onkokb"
    oncokb_actionable_collection = "oncokb_actionable"
    oncokb_genes_collection = "oncokb_genes"
    oncokb_public_collection = "oncokb_public"
    oncokb_genes_public_collection = "oncokb_genes_public"
    oncokb_cancer_genes_public_collection = "oncokb_cancer_genes_public"
    clinpgx_genes_public_collection = "clinpgx_genes_public"
    brcaexchange_collection = "brcaexchange"
    iarc_tp53_collection = "iarc_tp53"
    cosmic_collection = "cosmic"
    expression_collection = "hpaexpr"

[bam]
    bam_samples = "samples"
