[primary]
    users_collection = "users"
    roles_collection = "roles"
    permissions_collection = "permissions"
    notifications_collection = "notifications"

    insilico_genelist_collection = "insilico_genelists"
    aspc_collection = "asp_configs"
    asp_collection = "assay_specific_panels"

    blacklist_collection = "blacklist"
    annotations_collection = "annotation"
    samples_collection = "samples"
    sample_comments_collection = "sample_comments"
    finding_comments_collection = "finding_comments"
    reports_collection = "reports"
    variants_collection = "variants"
    anno_vep_collection = "anno_vep"
    cnvs_collection = "cnvs"
    fusions_collection = "fusions"
    transloc_collection = "translocations"
    biomarkers_collection = "biomarkers"
    pgx_collection = "pgx"
    coverage_collection = "panel_coverage"
    groupcov_collection = "group_coverage"
    rna_expression_collection = "rna_expression"
    rna_qc_collection = "rna_qc"
    rna_classification_collection = "rna_classification"
    reported_variants_collection = "reported_variants"

    vep_metadata_collection = "vep_metadata"
    hgnc_collection = "hgnc_genes"

[knowledgebase]
    civic_variants_collection = "civic_variants"
    civic_gene_collection = "civic_genes"
    oncokb_collection = "onkokb"
    oncokb_actionable_collection = "oncokb_actionable"
    oncokb_genes_collection = "oncokb_genes"
    oncokb_public_collection = "oncokb_public"
    oncokb_genes_public_collection = "oncokb_genes_public"
    oncokb_cancer_genes_public_collection = "oncokb_cancer_genes_public"
    clinpgx_genes_public_collection = "clinpgx_genes_public"
    brcaexchange_collection = "brcaexchange"
    iarc_tp53_collection = "iarc_tp53"
    cosmic_collection = "cosmic"
    cosmic_noncoding_collection = "cosmic_noncoding_variants"
    cosmic_targeted_collection = "cosmic_targeted_variants"
    cosmic_breakpoints_collection = "cosmic_breakpoints"
    cosmic_structural_collection = "cosmic_structural_variants"
    cosmic_cna_collection = "cosmic_copy_number"
    cosmic_fusion_collection = "cosmic_fusions"
    cosmic_expression_collection = "cosmic_gene_expression"
    cosmic_methylation_collection = "cosmic_methylation"
    cosmic_classification_collection = "cosmic_classifications"
    cosmic_classification_paper_collection = "cosmic_classification_papers"
    cosmic_cgc_collection = "cosmic_cancer_gene_census"
    cosmic_cgc_hallmarks_collection = "cosmic_cgc_hallmarks"
    cosmic_genes_collection = "cosmic_genes"
    cosmic_transcripts_collection = "cosmic_transcripts"
    cosmic_mutant_census_collection = "cosmic_census_gene_mutations"
    cosmic_resistance_collection = "cosmic_resistance_mutations"
    cosmic_mutation_census_collection = "cosmic_mutation_census"
    cosmic_signature_sbs_collection = "cosmic_signature_sbs"
    cosmic_signature_dbs_collection = "cosmic_signature_dbs"
    cosmic_signature_sv_collection = "cosmic_signature_sv"
    cosmic_actionability_collection = "cosmic_actionability"
    knowledgebase_versions_collection = "versions"
    expression_collection = "hpaexpr"

[bam]
    bam_samples = "samples"
